name: Testing output with workflow command

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: echo workflow command
        run: |
          echo "::error file=aria_role.tsx,line=1::⚠ eslint-plugin-jsx-a11y(aria-role): Elements with ARIA roles must use a valid, non-abstract ARIA role."
          echo "::error file=aria_role.tsx,line=1::╭─[aria_role.tsx:1:11]"
          echo "::error file=aria_role.tsx,line=1::1 │ <div role='foobar' />"
          echo "::error file=aria_role.tsx,line=1::·           ────────"
          echo "::error file=aria_role.tsx,line=1::╰────"
          echo "::error file=aria_role.tsx,line=1::help: Set a valid, non-abstract ARIA role for element with ARIA, `foobar` is an invalid aria role"
