name: Testing output with workflow command

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: echo workflow command
        run: |
          echo "::error file=aria_role.tsx,line=1,endLine=1,col=11,endColumn=19::⚠ eslint-plugin-jsx-a11y(aria-role): Elements with ARIA roles must use a valid, non-abstract ARIA role."
